#!/bin/sh

set -e 

> SUMMY.txt

M="ctrl ss_sg mixer arbiter copy fill encode"
for i in $M
do
  echo $i >> SUMMY.txt
  sh /p/fpga/ise/build_xst  $i
  /p/fpga/ise/iselog.pl xst/$i.log >> SUMMY.txt
  echo    >> SUMMY.txt
done
