#!/bin/sh

set -e 

ofile=SUMMARY.txt

> $ofile

M="ctrl ss_sg mixer arbiter copy fill fifo_control tpram ss_adma ch0 ch1"
for i in $M
do
  echo $i >> SUMMY.txt
  sh /p/fpga/ise/build_xst  $i
  /p/fpga/ise/iselog.pl xst/$i.log >> $ofile
  echo    >> $ofile
done
