#!/bin/sh

set -e 

ofile=SUMMARY.txt

> $ofile

M="ctrl ss_sg mixer arbiter copy fill fifo_control tpram ch wbm spi_usb codeout encode decode ss_adma top"
for i in $M
do
  echo $i >> $ofile
  sh /p/fpga/ise/build_xst  $i
  /p/fpga/ise/iselog.pl xst/$i.log >> $ofile
  echo    >> $ofile
done
